# 9주차
## 목표
자바의 예외 처리에 대해 학습하세요.

## 학습할 것  
+ 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
+ 자바가 제공하는 예외 계층 구조
+ Exception과 Error의 차이는?
+ RuntimeException과 RE가 아닌 것의 차이는?
+ 커스텀한 예외 만드는 방법

### 자바에서 예외처리 방법 (try, catch, throw, thorws, finally)
- 컴파일 시점에 발생하는 예외(Exception)
- 프로그램 실행시에 발생하는 예외(RuntimeException)

```java
// 예외처리 코드 및 실행 순서
public class Main {	
	public static void main(String[] args) {
		try {
			// 에러 발생 가능한 코드
			throw new Exception();	// 강제로 예외 발생
		} catch(Exception e) {
			// 에러 발생 시 수행
			e.printStackTrace()	// 오류 출력
			throw e;

		} finally {
			// 에러 발생 유무와 상관 없이 실행
		}
	}
}
```

#### throws 
> 현재 메서드에서 자신을 호출한 상위 메서드로 Exception을 발생

#### throw
> 억지로 에러 발생 & 현재 메서드의 에러를 처리한 후 상위 메서드에 에러 정보를 줌으로써 상위 메서드에서도 에러 발생을 감지

### 자바가 제공하는 예외 계층 구조
> 실행 시 발생할 수 있는 오류(Exception & Error)를 클래스로 정의, Object 크래스는 모든 클래스의 부모 클래스이기 때문에 Exception클래스와 Error클래스 역시 Object클래스의 자식들이다.

__Exception클래스__
> 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외

|예외 이름|설명|
|:--:|:--:|
|FileNotFoundException|존재하지 않는 파일의 이름을 입력한 경우 발생|
|ClassNotFoundException|클래스의 이름을 잘못 적었을 경우 발생|
|DataFormatException|입력한 데이터 형식이 잘못된 경우 발생|

__RuntimeException클래스__
> 프로그래머의 실수로 발생하는 예외

|예외 이름|설명|
|:--:|:--:|
|ArrayIndexOutOfBoundsException|배열의 범위를 벗어난 경우 발생|
|NullPointerException|값이 null인 참조변수의 멤버를 호출하려 하는 경우 발생|
|ClassCastException|클래스의 형변환을 잘못한 경우 발생|
|ArithmeticException|정수를 0으로 나누려고 하는 경우 발생|

### Exception과 error의 차이는?
__Exception__
> 컴퓨터 시스템의 동작 도중 예기치 않았던 이상 상태가 발생하여 수행중인 프로그램이 영향을 받는 것.
>> 발생하더라도 수습할 수 있는 비교적 덜 심각한 오류

__Error__
> 컴파일 시 문법적인 오류와 런타임 시 Null Pointer 참조와 같은 오류로 프로세스에 심각한 문제를 야기시켜 프로세스를 종료 시킬 수 있다.
>> 메모리 부족이나 Stack Overflow와 같이 발생하면 복구할 수 없는 심각한 오류

### RuntimeException과 RE가 아닌 것의 차이는?
__Checked Exception__
> 컴파일 시 체크되는 예외로 컴파일 전 예측이 가능하다.
>> thorws를 통해 예외를 던지거나 try catch 문을 이용해 예외를 처리해 주어야 한다.

__Unchecked Exception(RE)__
> 컴파일 시 체크되지 않으며 프로그램 실행 도중 발생하는 예외로 예측이 불가능하다.

### 커스텀한 예외 만드는 법
> 예외를 Checked로 할지 Unchecked로 만들지 정하고 만들어야 한다.
>> Checked 예외를 너무 자주 사용하면 API 사용자를 힘들게 만들 수 있기 때문에 적정선을 유지해야 한다.

```java
// ArithmeticException 정수를 0으로 나누려고 하는 경우 발생하는 예외 만들어보기
class CustomException extends Exception {
	DivideException(){
        super();
    }
    DivideException(String message){
        super(message);
    }
}

class Calculator{
    int left, right;
    public void setOprands(int left, int right){
        this.left = left;
        this.right = right;
    }
    public void divide(){
        if(this.right == 0){
            try {
                throw new DivideException("0으로 나누는 것은 허용되지 않습니다.");
            } catch (DivideException e) {
                e.printStackTrace();
            }
        }
        System.out.print(this.left / this.right);
    }

}
```